services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    expose:
      - '4306'
    volumes:
      - ./mysql:/var/lib/mysql
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management
    ports: [5672, 15672]
    expose:
      - '5672'